version: '2'

services:
    
    nodejsapp:
        #image: node_app
        build: .
        volumes:
            - ./config:/opt/app/config
            - ./io:/opt/app/io
            - ./modules:/opt/app/modules
            - ./package.json:/opt/app/package.json
            
        command: nodemon --legacy-watch io/api.js
        ports:
            - "3000:3000"
        # env_file:
        #     - ./Docker/env
        networks:
            webnet:
                aliases:
                    - nodejsapp

networks:
    webnet:
